@host = localhost:4001

// Server Live
GET http://{{host}}/api/liveness HTTP/1.1
content-type: application/json
 
###


// Server Live
GET http://{{host}}/api/liveness/ HTTP/1.1
content-type: application/json
 
###