---
development:
  dialect: mysql
  database: widgets
  user: user
  password: password
  host: 127.0.0.1
  pool: 5
  options:
    migration_table_name: migrations_and_seed

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/db_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/db_production?sslmode=disable"}}

